CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "tb_DinhMuc" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NamHoc" character varying(20) NOT NULL,
    "DinhMucGiangDay" numeric NOT NULL,
    "DinhMucNCKH" numeric NOT NULL,
    "DinhMucBoiDuong" numeric NOT NULL,
    "HeSoLopDong" numeric,
    "HeSoThucHanh" numeric,
    "GhiChu" text,
    CONSTRAINT "PK_tb_DinhMuc" PRIMARY KEY ("Id")
);

CREATE TABLE "tb_Khoa" (
    "MaKhoa" character varying(10) NOT NULL,
    "TenKhoa" character varying(100) NOT NULL,
    "Email" text,
    "DienThoai" text,
    CONSTRAINT "PK_tb_Khoa" PRIMARY KEY ("MaKhoa")
);

CREATE TABLE "tb_MonHoc" (
    "MaMH" character varying(10) NOT NULL,
    "TenMH" character varying(100) NOT NULL,
    "SoTinChi" integer NOT NULL,
    "HeDaoTao" text,
    CONSTRAINT "PK_tb_MonHoc" PRIMARY KEY ("MaMH")
);

CREATE TABLE "tb_BoMon" (
    "MaBM" character varying(10) NOT NULL,
    "TenBM" character varying(100) NOT NULL,
    "MaKhoa" character varying(10),
    "MoTa" text,
    CONSTRAINT "PK_tb_BoMon" PRIMARY KEY ("MaBM"),
    CONSTRAINT "FK_tb_BoMon_tb_Khoa_MaKhoa" FOREIGN KEY ("MaKhoa") REFERENCES "tb_Khoa" ("MaKhoa")
);

CREATE TABLE "tb_Lop" (
    "MaLop" character varying(10) NOT NULL,
    "SiSo" integer NOT NULL,
    "MaKhoa" character varying(10),
    "Nganh" text,
    "NamHoc" text,
    CONSTRAINT "PK_tb_Lop" PRIMARY KEY ("MaLop"),
    CONSTRAINT "FK_tb_Lop_tb_Khoa_MaKhoa" FOREIGN KEY ("MaKhoa") REFERENCES "tb_Khoa" ("MaKhoa")
);

CREATE TABLE "tb_VanBan" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SoVanBan" character varying(50) NOT NULL,
    "TenVanBan" character varying(500) NOT NULL,
    "TheLoai" character varying(50) NOT NULL,
    "NgayBanHanh" timestamp with time zone NOT NULL,
    "NamHoc" character varying(20),
    "CoQuanBanHanh" character varying(200),
    "NguoiKy" character varying(200),
    "TrichYeu" text,
    "FilePath" text,
    "FileName" text,
    "FileSize" bigint,
    "MaKhoa" character varying(10),
    "TrangThai" character varying(50),
    "NgayTao" timestamp with time zone,
    "NguoiTao" text,
    CONSTRAINT "PK_tb_VanBan" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_VanBan_tb_Khoa_MaKhoa" FOREIGN KEY ("MaKhoa") REFERENCES "tb_Khoa" ("MaKhoa") ON DELETE SET NULL
);

CREATE TABLE "tb_GiangVien" (
    "MaGV" character varying(10) NOT NULL,
    "TenGV" character varying(100) NOT NULL,
    "NgaySinh" timestamp with time zone,
    "DiaChi" text,
    "SDT" text,
    "Email" text,
    "MaKhoa" character varying(10),
    "MaBM" character varying(10),
    CONSTRAINT "PK_tb_GiangVien" PRIMARY KEY ("MaGV"),
    CONSTRAINT "FK_tb_GiangVien_tb_BoMon_MaBM" FOREIGN KEY ("MaBM") REFERENCES "tb_BoMon" ("MaBM"),
    CONSTRAINT "FK_tb_GiangVien_tb_Khoa_MaKhoa" FOREIGN KEY ("MaKhoa") REFERENCES "tb_Khoa" ("MaKhoa")
);

CREATE TABLE "tb_BoiDuong" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaGV" character varying(10) NOT NULL,
    "NoiDung" character varying(200) NOT NULL,
    "ChiTiet" character varying(200),
    "GioBoiDuong" integer NOT NULL,
    "NamHoc" character varying(20),
    "NgayThucHien" timestamp with time zone,
    "GhiChu" text,
    CONSTRAINT "PK_tb_BoiDuong" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_BoiDuong_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE CASCADE
);

CREATE TABLE "tb_LichCongTac" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NgayThang" timestamp with time zone NOT NULL,
    "ThoiGianBatDau" interval,
    "ThoiGianKetThuc" interval,
    "NoiDung" character varying(500) NOT NULL,
    "DiaDiem" character varying(200),
    "ThanhPhan" character varying(500),
    "ChuTri" character varying(200),
    "MaGV" character varying(10),
    "MaKhoa" character varying(10),
    "LoaiLich" character varying(50),
    "TrangThai" character varying(50),
    "GhiChu" text,
    "NgayTao" timestamp with time zone,
    CONSTRAINT "PK_tb_LichCongTac" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_LichCongTac_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE SET NULL,
    CONSTRAINT "FK_tb_LichCongTac_tb_Khoa_MaKhoa" FOREIGN KEY ("MaKhoa") REFERENCES "tb_Khoa" ("MaKhoa") ON DELETE SET NULL
);

CREATE TABLE "tb_MinhChung" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaGV" character varying(10) NOT NULL,
    "LoaiMinhChung" character varying(50) NOT NULL,
    "TieuDe" character varying(200) NOT NULL,
    "MoTa" text,
    "NamHoc" character varying(20),
    "IdNCKH" integer,
    "IdBoiDuong" integer,
    "IdNhiemVuKhac" integer,
    "FilePath" text NOT NULL,
    "FileName" text,
    "FileSize" bigint,
    "FileType" text,
    "NgayNop" timestamp with time zone NOT NULL,
    "TrangThai" character varying(50) NOT NULL,
    "NguoiDuyet" text,
    "NgayDuyet" timestamp with time zone,
    "GhiChuDuyet" text,
    CONSTRAINT "PK_tb_MinhChung" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_MinhChung_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE CASCADE
);

CREATE TABLE "tb_NghienCuuKhoaHoc" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaGV" character varying(10) NOT NULL,
    "TenDeTai" character varying(500) NOT NULL,
    "TheLoai" character varying(50) NOT NULL,
    "VaiTro" character varying(50),
    "GioNCKH" integer NOT NULL,
    "NamHoc" character varying(20),
    "NgayBatDau" timestamp with time zone,
    "NgayKetThuc" timestamp with time zone,
    "TrangThai" character varying(50),
    "MoTa" text,
    "FileMinhChung" text,
    CONSTRAINT "PK_tb_NghienCuuKhoaHoc" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_NghienCuuKhoaHoc_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE CASCADE
);

CREATE TABLE "tb_NhiemVuKhac" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaGV" character varying(10) NOT NULL,
    "CongViec" character varying(100) NOT NULL,
    "ChiTiet" character varying(200),
    "SoGio" integer NOT NULL,
    "NamHoc" character varying(20),
    "NgayThucHien" timestamp with time zone,
    "GhiChu" text,
    CONSTRAINT "PK_tb_NhiemVuKhac" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_NhiemVuKhac_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE CASCADE
);

CREATE TABLE "tb_PhanCong" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaGV" character varying(10) NOT NULL,
    "MaMH" character varying(10) NOT NULL,
    "MaLop" character varying(10) NOT NULL,
    "TietBatDau" integer NOT NULL,
    "SoTiet" integer NOT NULL,
    "Thu" integer NOT NULL,
    "ThoiGianHoc" text,
    "PhongHoc" text,
    "GhiChu" text,
    CONSTRAINT "PK_tb_PhanCong" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_PhanCong_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE CASCADE,
    CONSTRAINT "FK_tb_PhanCong_tb_Lop_MaLop" FOREIGN KEY ("MaLop") REFERENCES "tb_Lop" ("MaLop") ON DELETE CASCADE,
    CONSTRAINT "FK_tb_PhanCong_tb_MonHoc_MaMH" FOREIGN KEY ("MaMH") REFERENCES "tb_MonHoc" ("MaMH") ON DELETE CASCADE
);

CREATE TABLE "tb_TaiKhoan" (
    "MaTK" character varying(50) NOT NULL,
    "MatKhau" text NOT NULL,
    "ChucVu" character varying(10) NOT NULL,
    "MaGV" character varying(10),
    "MaKhoa" character varying(10),
    "MaBM" character varying(10),
    CONSTRAINT "PK_tb_TaiKhoan" PRIMARY KEY ("MaTK"),
    CONSTRAINT "FK_tb_TaiKhoan_tb_BoMon_MaBM" FOREIGN KEY ("MaBM") REFERENCES "tb_BoMon" ("MaBM") ON DELETE RESTRICT,
    CONSTRAINT "FK_tb_TaiKhoan_tb_GiangVien_MaGV" FOREIGN KEY ("MaGV") REFERENCES "tb_GiangVien" ("MaGV") ON DELETE RESTRICT,
    CONSTRAINT "FK_tb_TaiKhoan_tb_Khoa_MaKhoa" FOREIGN KEY ("MaKhoa") REFERENCES "tb_Khoa" ("MaKhoa") ON DELETE RESTRICT
);

CREATE INDEX "IX_tb_BoiDuong_MaGV" ON "tb_BoiDuong" ("MaGV");

CREATE INDEX "IX_tb_BoMon_MaKhoa" ON "tb_BoMon" ("MaKhoa");

CREATE INDEX "IX_tb_GiangVien_MaBM" ON "tb_GiangVien" ("MaBM");

CREATE INDEX "IX_tb_GiangVien_MaKhoa" ON "tb_GiangVien" ("MaKhoa");

CREATE INDEX "IX_tb_LichCongTac_MaGV" ON "tb_LichCongTac" ("MaGV");

CREATE INDEX "IX_tb_LichCongTac_MaKhoa" ON "tb_LichCongTac" ("MaKhoa");

CREATE INDEX "IX_tb_Lop_MaKhoa" ON "tb_Lop" ("MaKhoa");

CREATE INDEX "IX_tb_MinhChung_MaGV" ON "tb_MinhChung" ("MaGV");

CREATE INDEX "IX_tb_NghienCuuKhoaHoc_MaGV" ON "tb_NghienCuuKhoaHoc" ("MaGV");

CREATE INDEX "IX_tb_NhiemVuKhac_MaGV" ON "tb_NhiemVuKhac" ("MaGV");

CREATE INDEX "IX_tb_PhanCong_MaGV" ON "tb_PhanCong" ("MaGV");

CREATE INDEX "IX_tb_PhanCong_MaLop" ON "tb_PhanCong" ("MaLop");

CREATE INDEX "IX_tb_PhanCong_MaMH" ON "tb_PhanCong" ("MaMH");

CREATE INDEX "IX_tb_TaiKhoan_MaBM" ON "tb_TaiKhoan" ("MaBM");

CREATE INDEX "IX_tb_TaiKhoan_MaGV" ON "tb_TaiKhoan" ("MaGV");

CREATE INDEX "IX_tb_TaiKhoan_MaKhoa" ON "tb_TaiKhoan" ("MaKhoa");

CREATE INDEX "IX_tb_VanBan_MaKhoa" ON "tb_VanBan" ("MaKhoa");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206032019_InitialPostgreSQLSetupFinal', '8.0.11');

COMMIT;

