// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeacherScheduleAPI.Data;

#nullable disable

namespace TeacherScheduleAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206032019_InitialPostgreSQLSetupFinal")]
    partial class InitialPostgreSQLSetupFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeacherScheduleAPI.Models.BoMon", b =>
                {
                    b.Property<string>("MaBM")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenBM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaBM");

                    b.HasIndex("MaKhoa");

                    b.ToTable("tb_BoMon");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.BoiDuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("GioBoiDuong")
                        .HasColumnType("integer");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MaGV");

                    b.ToTable("tb_BoiDuong");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.DinhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DinhMucBoiDuong")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DinhMucGiangDay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DinhMucNCKH")
                        .HasColumnType("numeric");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<decimal?>("HeSoLopDong")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HeSoThucHanh")
                        .HasColumnType("numeric");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("tb_DinhMuc");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("MaBM")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SDT")
                        .HasColumnType("text");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaGV");

                    b.HasIndex("MaBM");

                    b.HasIndex("MaKhoa");

                    b.ToTable("tb_GiangVien");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("tb_Khoa");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.LichCongTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuTri")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("LoaiLich")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MaGV")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayThang")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThanhPhan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeSpan?>("ThoiGianBatDau")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ThoiGianKetThuc")
                        .HasColumnType("interval");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("tb_LichCongTac");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NamHoc")
                        .HasColumnType("text");

                    b.Property<string>("Nganh")
                        .HasColumnType("text");

                    b.Property<int>("SiSo")
                        .HasColumnType("integer");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("tb_Lop");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.MinhChung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("text");

                    b.Property<int?>("IdBoiDuong")
                        .HasColumnType("integer");

                    b.Property<int?>("IdNCKH")
                        .HasColumnType("integer");

                    b.Property<int?>("IdNhiemVuKhac")
                        .HasColumnType("integer");

                    b.Property<string>("LoaiMinhChung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiDuyet")
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaGV");

                    b.ToTable("tb_MinhChung");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HeDaoTao")
                        .HasColumnType("text");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("integer");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaMH");

                    b.ToTable("tb_MonHoc");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.NghienCuuKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileMinhChung")
                        .HasColumnType("text");

                    b.Property<int>("GioNCKH")
                        .HasColumnType("integer");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaGV");

                    b.ToTable("tb_NghienCuuKhoaHoc");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.NhiemVuKhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CongViec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoGio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaGV");

                    b.ToTable("tb_NhiemVuKhac");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.PhanCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PhongHoc")
                        .HasColumnType("text");

                    b.Property<int>("SoTiet")
                        .HasColumnType("integer");

                    b.Property<string>("ThoiGianHoc")
                        .HasColumnType("text");

                    b.Property<int>("Thu")
                        .HasColumnType("integer");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMH");

                    b.ToTable("tb_PhanCong");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTK")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaBM")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaGV")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTK");

                    b.HasIndex("MaBM");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("tb_TaiKhoan");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.VanBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoQuanBanHanh")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("NgayBanHanh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("SoVanBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenVanBan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrichYeu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaKhoa");

                    b.ToTable("tb_VanBan");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.BoMon", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.BoiDuong", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.GiangVien", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("MaBM");

                    b.HasOne("TeacherScheduleAPI.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.Navigation("BoMon");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.LichCongTac", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeacherScheduleAPI.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.Lop", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.MinhChung", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.NghienCuuKhoaHoc", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.NhiemVuKhac", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.PhanCong", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherScheduleAPI.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherScheduleAPI.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.TaiKhoan", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("MaBM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeacherScheduleAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeacherScheduleAPI.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoMon");

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("TeacherScheduleAPI.Models.VanBan", b =>
                {
                    b.HasOne("TeacherScheduleAPI.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Khoa");
                });
#pragma warning restore 612, 618
        }
    }
}
